services:
  mariadb:
    image: mariadb:11
    container_name: community-mariadb
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: community
      MARIADB_USER: community
      MARIADB_PASSWORD: community1234
      TZ: Asia/Seoul
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: community-redis
    command: ["redis-server" , "--appendonly", "yes"]
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  app:
    build: .
    container_name: community-app
    depends_on:
      - mariadb
      - redis
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/community
      SPRING_DATASOURCE_USERNAME: community
      SPRING_DATASORUCE_PASSWORD: community1234
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_PROFILES_ACTIVE: docker
    restart: unless-stopped

volumes:
  mariadb_data:
  redis_data:
